config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :stories     
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  
  resources :stories do
    resource :like, module: :stories
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:show]

  root to: 'stories#index'
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :likes

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true  

  def published?
    published_at?
	end
	  
end

app/controllers/admin/stories_controller.rb
module Admin
  class StoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Story.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Story.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/stories/likes_controller.rb
class Stories::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @story.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @story }
      format.js
    end
  end

  def destroy
    @story.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @story }
      format.js
    end
  end

  private

    def set_post
      @story = Story.find(params[:story_id])
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  load_and_authorize_resource

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.order("updated_at DESC")
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    #@story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = current_user

    @story.published_at = Time.zone.now if publishing?   

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    @story.published_at = Time.zone.now if publishing?
    @story.published_at = nil if unpublishing?

    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def story_params
      params.require(:story).permit(:user_id, :title, :body, :tags)
    end
    
    def publishing?
      params[:commit] == "Publish"
    end

    def unpublishing?
      params[:commit] == "Unpublish"
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control full-height pad', placeholder: "Give your story a title" %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, size: "50x15", class: 'form-control pad', id:'content',placeholder: "Start Writing..." %>
  </div>

  <div class="form-group">
    <%= form.text_field :tags, class: 'form-control pad', placeholder: "Tags..." %>
  </div>

  <div class="form-group">
    <% if story.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', story, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <% if @story.published? %>
      <%= form.submit "Update", class: "btn btn-primary" %>
      <%= form.submit "Unpublish", class: "btn btn-default" %>
    <% else %>
      <%= form.submit "Publish", class: "btn btn-primary" %>
      <%= form.submit "Save as Draft", class: "btn btn-default" %>
    <% end %>

    <% if story.persisted? %>
      <%= link_to "Cancel", story, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", stories_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
$('#content').on( 'change keyup keydown paste cut', 'textarea', function (){
  $(this).height(0).height(this.scrollHeight);
}).find('textarea').change();

</script>

app/views/stories/_likes.html.erb
<% if user_signed_in? && current_user.likes?(story) %>
  <%= link_to story_like_path(story), method: :delete do %>
		<i class="fa fa-heart text-hearted"></i>
	<% end %>
<% else %>
  <%= link_to story_like_path(story), method: :story do %>
  	<i class="fa fa-heart text-muted"></i>
  <% end %>
<% end %>

<%= story.likes.count %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<% if current_user %>
	<%= render 'form', story: @story %>
<% end %>

app/views/stories/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Latest Stories</h1>
  </div>

  <div class="col-sm-6 text-right">
  <% if can? :create, Story %>
    <%= link_to new_story_path, class: 'btn btn-primary' do %>
      Add New Story
    <% end %>
  <% end %>
  </div>
</div>

<% @stories.each do |story| %>
  <% if story.published_at %>
    <%= content_tag :div, id: dom_id(story), class: dom_class(story) do %>
      <div class="jumbotron story">    
        <h3><%= link_to story.title, story if can? :read, story %></h3>
        <p><em>Written by: <%= story.user.name %></em></p>
        <%= render partial: "likes", locals: {story: story} %>
        <p><%= markdown(story.body.truncate(300,seperator: '\n')) %></p>                    
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/stories/new.html.erb
<%= render 'form', story: @story %>

app/views/stories/show.html.erb
<div class="page-header">
  
  <p><%= link_to stories_path, class: 'btn-sm btn-default' do %>
    <span class="glyphicon glyphicon-list-alt">All Stories</span>
  <% end %></p>
</div>

<div class="story jumbotron">
 
<div id="story_<%= @story.id %>_likes" class="float-right">
	<%= render partial: "likes", locals: {story: @story} %>
</div>
  <% if can? :update, @story %>
    <%= link_to "Edit", edit_story_path(@story), class: "btn btn-primary float-right" %>
  <% end %>

	<% if @story.published? %>
	  <span class="btn btn-info">Published</span>
	<% else %>
	  <span class="btn-lg btn-secondary">Draft</span>
	<% end %>

	<h1><%= @story.title %></h1>
	<p><em>Written by <%= @story.user.name %></em></p>

	<p><%= markdown(@story.body) %></p>

	<p><em>Tags:<%= @story.tags %></em></p>
</div>